// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwxezgpnjpntbvihemvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3eGV6Z3BuanBudGJ2aWhlbXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzAxOTEsImV4cCI6MjA2Mzk0NjE5MX0.i2jLNnEB58htzPeKu4D3j37qPwwMW1GhIQHLoycWdR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);